### ISSUE TITLE
ansible task not working (perfectly)

### ISSUE THREAD

**Issue by timfeirg** [juicedata/juicefs-quickstart#1]
除开客服群里交换过的信息, 我的环境信息如下:

```shell
[root@qcloud-dev5 ~]# cat /etc/fstab
/dev/vda1            /                    ext3       noatime,acl,user_xattr 1 1
proc                 /proc                proc       defaults              0 0
sysfs                /sys                 sysfs      noauto                0 0
debugfs              /sys/kernel/debug    debugfs    noauto                0 0
devpts               /dev/pts             devpts     mode=0620,gid=5       0 0
/dev/vdb             /data                 ext4       noatime,acl,user_xattr 1 1
einqcloud /jfs juicefs _netdev 0 0
[root@qcloud-dev5 ~]# mount | grep einqcloud
JuiceFS:einqcloud on /jfs type fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
[root@qcloud-dev5 ~]# juicefs version
JuiceFS version 4.3.5 (2019-02-23 5af6aa4)
[root@qcloud-test1 /]# cat /etc/*release*
CentOS Linux release 7.5.1804 (Core)
Derived from Red Hat Enterprise Linux 7.5 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core)
CentOS Linux release 7.5.1804 (Core)
cpe:/o:centos:centos:7

```

我自己修改后的 task 如下:

```yaml
---

- set_fact:
    jfs_bin: /usr/local/bin/juicefs
    jfs_name: einqcloud
    jfs_path: /jfs
    jfs_bucket: "xxx"

- include_vars: "secrets.yml"

- name: install JuiceFS client
  get_url:
    url: https://juicefs.com/static/juicefs
    mode: 0755
    dest: "{{jfs_bin}}"

- name: fetch JuiceFS config
  command: "{{jfs_bin}} auth {{jfs_name}} --token {{jfs_token}} --accesskey={{jfs_accesskey}} --secretkey={{jfs_secretkey}} --bucket={{jfs_bucket}}"
  args:
    creates: /root/.juicefs/{{jfs_name}}.conf

- name: mount JuiceFS
  command: "{{jfs_bin}} mount {{jfs_name}} {{jfs_path}}"
  args:
    creates: "{{jfs_path}}"

- name: update fstab
  mount:
    path: "{{jfs_path}}"
    src: "{{jfs_name}}"
    fstype: juicefs
    opts: _netdev
    state: present
```
